exclude: '\.snap$'
repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b2
    hooks:
    - id: black
      python_version: python3.6
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
    - id: flake8
      log_file: '.artifacts/flake8.log'
    - id: requirements-txt-fixer
